/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_Native_Stub */

#ifndef _Included_com_example_Native_Stub
#define _Included_com_example_Native_Stub
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_Native_Stub
 * Method:    GetSample
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_example_Native_00024Stub_GetSample
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
