/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_Native */

#ifndef _Included_com_example_Native
#define _Included_com_example_Native
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_Native
 * Method:    GetSample
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_example_Native_GetSample__
  (JNIEnv *, jclass);

/*
 * Class:     com_example_Native
 * Method:    GetSample
 * Signature: (ILjava/lang/String;[I)I
 */
JNIEXPORT jint JNICALL Java_com_example_Native_GetSample__ILjava_lang_String_2_3I
  (JNIEnv *, jclass, jint, jstring, jintArray);

#ifdef __cplusplus
}
#endif
#endif
