/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_Sample */

#ifndef _Included_com_example_Sample
#define _Included_com_example_Sample
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_Sample
 * Method:    GetSample
 * Signature: (ILjava/lang/String;[I)I
 */
JNIEXPORT jint JNICALL Java_com_example_Sample_GetSample
  (JNIEnv *, jclass, jint, jstring, jintArray);

#ifdef __cplusplus
}
#endif
#endif
